name: Deploy react app to github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get all node modules
        run: yarn
      - name: Make an optimized build
        run: yarn build
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github-token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build

