name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install  # runs `yarn install`

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build  # runs `yarn build`
